// BIO100 Ch16-18 Flashcards
// Attach globally: window.FLASHCARDS
window.FLASHCARDS = [
  { q:"Primary function of the urinary system?", a:"Maintain homeostasis by filtering blood and removing wastes as urine.", topic:"Urinary", ch:16 },
  { q:"Basic functional unit of the kidney?", a:"Nephron — millions per kidney, each filtering blood plasma.", topic:"Urinary", ch:16 },
  { q:"Urine flow through the tract?", a:"Kidney -> Ureter -> Urinary bladder -> Urethra.", topic:"Urinary", ch:16 },
  { q:"Five functions of the digestive system (ordered)?", a:"Ingestion -> Propulsion -> Digestion (mechanical+chemical) -> Absorption -> Defecation.", topic:"Digestive", ch:16 },
  { q:"Where does most nutrient absorption occur?", a:"Jejunum and ileum of the small intestine.", topic:"Digestive", ch:16 },
  { q:"Duodenum’s key role?", a:"Completes most chemical breakdown using enzymes and bile.", topic:"Digestive", ch:16 },
  { q:"Two salivary agents?", a:"Lysozyme (antibacterial) and salivary amylase (starts starch digestion).", topic:"Digestive", ch:16 },
  { q:"Liver’s digestive contribution?", a:"Produces bile to emulsify fats.", topic:"Digestive", ch:16 },
  { q:"Pancreas role in digestion?", a:"Releases enzymes for carbs, fats, and proteins into the small intestine.", topic:"Digestive", ch:16 },
  { q:"Arteries vs veins vs capillaries?", a:"Arteries carry blood away; veins return blood; capillaries exchange.", topic:"Cardio", ch:16 },
  { q:"Heart AV valves and semilunar valves?", a:"AV: tricuspid (R) & bicuspid/mitral (L). Semilunar: pulmonary & aortic.", topic:"Cardio", ch:16 },
  { q:"Path of air to alveoli?", a:"Nose -> Pharynx -> Larynx -> Trachea -> Bronchi -> Bronchioles -> Alveoli.", topic:"Respiratory", ch:16 },
  { q:"Inspiration mechanics?", a:"Diaphragm/intercostals contract -> thoracic volume up -> pressure down -> air in.", topic:"Respiratory", ch:16 },
  { q:"Left vs right lung lobes?", a:"Left: 2 lobes. Right: 3 lobes.", topic:"Respiratory", ch:16 },
  { q:"Bones in adult skeleton; axial vs appendicular counts?", a:"Total ~206 bones. Axial 80; Appendicular 126.", topic:"Skeletal", ch:16 },
  { q:"Function of intervertebral discs?", a:"Fibrocartilage pads between vertebrae that cushion and permit motion.", topic:"Skeletal", ch:16 },
  { q:"True vs false vs floating ribs?", a:"True (7 pairs); False (5 pairs); Floating (2 pairs).", topic:"Skeletal", ch:16 },
  { q:"Three muscle types + key property", a:"Skeletal (striated, voluntary); Cardiac (striated, involuntary); Smooth (non-striated, involuntary).", topic:"Muscular", ch:16 },
  { q:"Functional unit inside skeletal muscle fibers?", a:"Sarcomere within myofibrils.", topic:"Muscular", ch:16 },
  { q:"Tendons vs ligaments?", a:"Tendons connect muscle to bone; ligaments connect bone to bone.", topic:"Muscular", ch:16 },
  { q:"Neuron: dendrites vs axon?", a:"Dendrites receive signals; axon carries impulses away from cell body.", topic:"Nervous", ch:16 },
  { q:"CNS vs PNS (afferent vs efferent)?", a:"CNS: brain & spinal cord. PNS: all nerves. Afferent -> CNS; Efferent -> effectors.", topic:"Nervous", ch:16 },
  { q:"Brain regions (4 major)", a:"Cerebrum, Diencephalon, Brainstem, Cerebellum.", topic:"Nervous", ch:16 },
  { q:"Hypothalamus hormones released from posterior pituitary?", a:"Oxytocin and ADH are produced by hypothalamus, stored/released by posterior pituitary.", topic:"Endocrine", ch:16 },
  { q:"Two anterior pituitary hormones + roles", a:"GH (growth); TSH (stimulates thyroid). Also PRL, FSH, LH, ACTH.", topic:"Endocrine", ch:16 },
  { q:"Thyroid vs parathyroid Ca2+ effects?", a:"Calcitonin lowers blood Ca2+; PTH raises blood Ca2+.", topic:"Endocrine", ch:16 },
  { q:"Adrenal medulla vs cortex products?", a:"Medulla: epi/norepi. Cortex: aldosterone, cortisol, androgens/estrogens.", topic:"Endocrine", ch:16 },
  { q:"Pancreatic hormones and glucose?", a:"Insulin lowers; glucagon raises blood glucose.", topic:"Endocrine", ch:16 },
  { q:"Two main functions of lymphatic system?", a:"Return leaked interstitial fluid to blood; immune surveillance/defense.", topic:"Immune", ch:17 },
  { q:"Primary vs secondary lymphoid tissues?", a:"Primary: bone marrow, thymus. Secondary: spleen, tonsils, Peyer's patches, appendix.", topic:"Immune", ch:17 },
  { q:"Innate vs adaptive key differences?", a:"Innate: nonspecific, immediate. Adaptive: antigen-specific, memory.", topic:"Immune", ch:17 },
  { q:"Active vs passive immunity examples?", a:"Active: infection or vaccination. Passive: maternal or donated antibodies.", topic:"Immune", ch:17 },
  { q:"Virus vs bacteria in one line", a:"Viruses are acellular and replicate inside cells; bacteria are unicellular organisms.", topic:"Immune", ch:17 },
  { q:"Male tract (condensed)?", a:"Testes -> epididymis -> vas deferens -> ejaculatory duct -> urethra; glands: seminal, prostate, bulbourethral.", topic:"Repro", ch:18 },
  { q:"Semen components by percent?", a:"~60% seminal vesicles, ~33% prostate, plus bulbourethral secretions and sperm.", topic:"Repro", ch:18 },
  { q:"Sperm parts & roles?", a:"Head (DNA+acrosome), midpiece (mitochondria), tail (motility).", topic:"Repro", ch:18 },
  { q:"Female internal organs (key roles)?", a:"Ovaries; uterine tubes (fertilization); uterus (nourish); vagina (intercourse/childbirth).", topic:"Repro", ch:18 },
  { q:"Oogenesis numbers to remember?", a:"~2M at birth; ~400k by puberty; <~500 ovulated lifetime.", topic:"Repro", ch:18 },
  { q:"Menstrual cycle phases & day 14?", a:"Days 1-5 menstrual; 6-14 proliferative; ~Day 14 ovulation; 15-28 secretory.", topic:"Repro", ch:18 },
  { q:"Fertilization + implantation sites?", a:"Fertilization usually in uterine tube; implantation in uterine wall.", topic:"Repro", ch:18 },
  { q:"Zygote -> embryo -> fetus timing?", a:"Zygote (first cell), embryo (to week 8), fetus (week 9 to birth).", topic:"Repro", ch:18 }
];
